// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBCXCpweNRJdPT4BfNPRR_BVE_gZ-SZO0',
    appId: '1:801530941214:web:8323f428ebb8988d64030f',
    messagingSenderId: '801530941214',
    projectId: 'fir-application-fc31e',
    authDomain: 'fir-application-fc31e.firebaseapp.com',
    storageBucket: 'fir-application-fc31e.appspot.com',
    measurementId: 'G-LYYPMVEHLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGhqCFyNuFh3oFZ7OFupoWyjrc7wuVB_U',
    appId: '1:801530941214:android:38a5c86b5e7c9eb564030f',
    messagingSenderId: '801530941214',
    projectId: 'fir-application-fc31e',
    storageBucket: 'fir-application-fc31e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtZlJ6FLkJsgFRqdjqCDK66LEkp8MEZ44',
    appId: '1:801530941214:ios:5b4b9ea1b4d74c6664030f',
    messagingSenderId: '801530941214',
    projectId: 'fir-application-fc31e',
    storageBucket: 'fir-application-fc31e.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtZlJ6FLkJsgFRqdjqCDK66LEkp8MEZ44',
    appId: '1:801530941214:ios:5b4b9ea1b4d74c6664030f',
    messagingSenderId: '801530941214',
    projectId: 'fir-application-fc31e',
    storageBucket: 'fir-application-fc31e.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBCXCpweNRJdPT4BfNPRR_BVE_gZ-SZO0',
    appId: '1:801530941214:web:ac3867ade120a9cf64030f',
    messagingSenderId: '801530941214',
    projectId: 'fir-application-fc31e',
    authDomain: 'fir-application-fc31e.firebaseapp.com',
    storageBucket: 'fir-application-fc31e.appspot.com',
    measurementId: 'G-X74V5QFF18',
  );
}
